### ISSUE TITLE
suggestion : add bypass an ip

### ISSUE THREAD

**Issue by teracube** [DarkWav/VPNGuard-LTS#1]
suggestion 

add bypass.yml on the config to permit an ip to connect if this ip is recognized as a proxy by API
thanks

**Comment by DarkWav** [comment]
Thanks for the Feature Request! 
I have added whitelists for specific player names to the plugin.
You can download the LTS Patch API_3.0.0_v3 [here](https://github.com/DarkWav/VPNGuard-LTS/raw/master/releases/VPNGuard_v1.0.7-patch3.phar)
Whitelisting false blocked IPs from private households it pretty useless as the internet provider changes these constantly, and you would have to re-whitelist players on a daily basis in most cases. With XBoxLive-Auth or some Auth Plugin whitelisting player names should be safe to use.
